### ISSUE TITLE
[ErrorException]   Declaration of MyBB\Auth\AuthManager::callCustomCreator() should be compatible with Illuminate\Auth\AuthManager::callCustomCreator

### ISSUE THREAD

**Issue by chope1** [mybb/mybb2#182] opened 2016-02-13 14:37 UTC
This issue is not solved yet?
`[ErrorException]
  Declaration of MyBB\Auth\AuthManager::callCustomCreator() should be compati
  ble with Illuminate\Auth\AuthManager::callCustomCreator($name, array $confi
  g)
`

**Comment by euantorano** [comment] 2016-02-13 14:39
It will be fixed this weekend, I'm working on it. The issue is in the Auth library, not the core.

**Closed** 2016-02-13 14:42 UTC
Labels: duplicate

**Comment by ATofighi** [comment] 2016-02-13 14:43
https://github.com/mybb/Auth/issues/5

**Comment by chope1** [comment] 2016-02-15 13:08
Thanks @euantorano  and @ATofighi 
It was successfully published, however, there are some errors in login as the admin with 
Username - admin
Password - passoword.
After clicking login, it will load and return to homepage without being authenticated,
Registration is trowing error in database.
In trying to post as a guest I will be redirected to error page.
Thanks.

**Comment by euantorano** [comment] 2016-02-15 17:30
Yeah, I noticed these and am still working to fix them. I'm not currently sure what's wrong, but I'll get it working this week. There are a few places throwing errors due to framework changes.

**Comment by euantorano** [comment] 2016-02-15 17:53
I also need to get permission checks rewritten this week/weekend too.

**Comment by chope1** [comment] 2016-02-15 18:54
ok. Thanks. The forum looks exciting, can't wait for the release.
Modern and quality!

**Comment by euantorano** [comment] 2016-02-21 14:46
Ok, logins ar enow fixed. The problem was none of the routes were using the web middleware. That's one problem down, 100s to go :wink:

**Comment by chope1** [comment] 2016-02-26 17:41
I can't reinstall it, getting this error - 
  [ErrorException]
  php_strip_whitespace(C:\...): failed to open stream: Permission denied

Script php artisan optimize handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

**Comment by euantorano** [comment] 2016-02-26 17:46
Looks like a permissions error on your system. You're running Windows, right? Can you run 

php artisan optimize --verbose

**Comment by chope1** [comment] 2016-02-27 05:12
Yes, I am running it on Windows using Xampp server, I rand the code you provided (php artisan optimize --verbose). and got this output
`
  [ErrorException]
  php_strip_whitespace(C:\xampp\htdocs\askng): failed to open stream: Permiss
  ion denied


Exception trace:
 () at C:\xampp\htdocs\askng\vendor\classpreloader\classpreloader\src\ClassPreloader.php:124
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 php_strip_whitespace() at C:\xampp\htdocs\askng\vendor\classpreloader\classpreloader\src\ClassPreloader.php:124
 ClassPreloader\ClassPreloader->getCode() at C:\xampp\htdocs\askng\vendor\laravel\framework\src\Illuminate\Foundation\Console\OptimizeCommand.php:83
 Illuminate\Foundation\Console\OptimizeCommand->compileClasses() at C:\xampp\htdocs\askng\vendor\laravel\framework\src\Illuminate\Foundation\Console\OptimizeCommand.php:64
 Illuminate\Foundation\Console\OptimizeCommand->fire() at n/a:n/a
 call_user_func_array() at C:\xampp\htdocs\askng\bootstrap\cache\compiled.php:1232
 Illuminate\Container\Container->call() at C:\xampp\htdocs\askng\vendor\laravel\framework\src\Illuminate\Console\Command.php:169
 Illuminate\Console\Command->execute() at C:\xampp\htdocs\askng\vendor\symfony\console\Command\Command.php:259
 Symfony\Component\Console\Command\Command->run() at C:\xampp\htdocs\askng\vendor\laravel\framework\src\Illuminate\Console\Command.php:155
 Illuminate\Console\Command->run() at C:\xampp\htdocs\askng\vendor\symfony\console\Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at C:\xampp\htdocs\askng\vendor\symfony\console\Application.php:192
 Symfony\Component\Console\Application->doRun() at C:\xampp\htdocs\askng\vendor\symfony\console\Application.php:123
 Symfony\Component\Console\Application->run() at C:\xampp\htdocs\askng\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:107
 Illuminate\Foundation\Console\Kernel->handle() at C:\xampp\htdocs\askng\artisan:36
`
I really don't understand the issue with Permission on Windows, I installed many Laravel  and many other Laravel packages in my Windows without any permission error.
Maybe I should try it on my Linux to see how it works.
Thanks.

**Comment by euantorano** [comment] 2016-02-27 07:55
Interesting. I don't use Windows so I'd never noticed it. I'll have a look today.

**Comment by chope1** [comment] 2016-02-27 08:14
ok, thank @euantorano 
I will also try to install it on my Ubuntu Desktop Os, let me see if it works.
Thanks.
